FROM ubuntu:latest

# Path: dockerfile
WORKDIR /app

# 환경 변수를 설정하여 대화식 입력을 방지합니다.
ENV DEBIAN_FRONTEND=noninteractive


# Install python3.9 and pip3
RUN apt-get update -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt install python3.9 -y




# python3.9을 기본으로 설정
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 3
RUN update-alternatives --config python

# python3-pip 설치
RUN apt install python3-pip -y

# 다른 여러 python 패키지들을 설치하기 위해 필요
RUN apt-get install python3-distutils -y

# RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install inference

# Debian계열인 ubuntu 에서 OpenGL을 사용하기 위해서는 libgl1-mesa-glx 패키지를 설치해야 합니다.
RUN apt-get install libgl1-mesa-glx -y

# docker에서 GUI를 사용하기 위해서는 다음과 같은 패키지를 설치
RUN apt-get install libqt5gui5 libqt5core5a libqt5widgets5 -y
RUN apt-get install libxcb-xinerama0 -y

# Docker에서 GUI를 사용하기 위해서는 환경변수를 설정해야 합니다.-> 이건 안해도 됐음 난
# ENV QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins/platforms

# opencv-python 재설치 (필요시 사용)
# RUN python3 -m pip uninstall opencv-python \
#     && python3 -m pip install opencv-python==4.8.0.76

COPY . /app

CMD ["python3", "money_test.py"]